#! /bin/sh

if [ -d tmp ]; then
  rm -rf tmp
fi

mkdir tmp
cd ./tmp/
  cp ../src_data/rRNA/sequences.fna sequences.fna
  cp ../src_data/alignment/green_genes.align .
  mothur "#align.seqs(candidate=sequences.fna, template=green_genes.align)"
  mothur "#filter.seqs(fasta=sequences.align,vertical=T)"
cd ..

if [ -d alignment ]; then
  rm -rf alignment
fi
mkdir alignment

cd ./alignment/
  cp ../tmp/sequences.filter.fasta sequences.align
  java -jar ../lib/readseq.jar -f Phylip -o sequences.phylip sequences.align
cd ..

rm tmp/*
cd ./tmp/
  cp ../alignment/sequences.phylip .
  raxml -s sequences.phylip \
        -n tree.txt         \
        -m GTRMIX           \
        -o Cellvibrio
        #-q groups.txt \
        #-f t \
        #-N 100
cd ..

if [ -d tree ]; then
  rm -rf tree
fi
mkdir tree
cp tmp/RAxML_result.tree.txt tree/rRNA.newick

rm -rf tmp
